# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/s98420/simplessd-standalone

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/s98420/simplessd-standalone

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/s98420/simplessd-standalone/CMakeFiles /home/s98420/simplessd-standalone/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/s98420/simplessd-standalone/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named simplessd-standalone

# Build rule for target.
simplessd-standalone: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 simplessd-standalone
.PHONY : simplessd-standalone

# fast build rule for target.
simplessd-standalone/fast:
	$(MAKE) -f CMakeFiles/simplessd-standalone.dir/build.make CMakeFiles/simplessd-standalone.dir/build
.PHONY : simplessd-standalone/fast

#=============================================================================
# Target rules for targets named simplessd

# Build rule for target.
simplessd: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 simplessd
.PHONY : simplessd

# fast build rule for target.
simplessd/fast:
	$(MAKE) -f simplessd/CMakeFiles/simplessd.dir/build.make simplessd/CMakeFiles/simplessd.dir/build
.PHONY : simplessd/fast

#=============================================================================
# Target rules for targets named mcpat

# Build rule for target.
mcpat: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mcpat
.PHONY : mcpat

# fast build rule for target.
mcpat/fast:
	$(MAKE) -f simplessd/lib/mcpat/CMakeFiles/mcpat.dir/build.make simplessd/lib/mcpat/CMakeFiles/mcpat.dir/build
.PHONY : mcpat/fast

bil/entry.o: bil/entry.cc.o

.PHONY : bil/entry.o

# target to build an object file
bil/entry.cc.o:
	$(MAKE) -f CMakeFiles/simplessd-standalone.dir/build.make CMakeFiles/simplessd-standalone.dir/bil/entry.cc.o
.PHONY : bil/entry.cc.o

bil/entry.i: bil/entry.cc.i

.PHONY : bil/entry.i

# target to preprocess a source file
bil/entry.cc.i:
	$(MAKE) -f CMakeFiles/simplessd-standalone.dir/build.make CMakeFiles/simplessd-standalone.dir/bil/entry.cc.i
.PHONY : bil/entry.cc.i

bil/entry.s: bil/entry.cc.s

.PHONY : bil/entry.s

# target to generate assembly for a file
bil/entry.cc.s:
	$(MAKE) -f CMakeFiles/simplessd-standalone.dir/build.make CMakeFiles/simplessd-standalone.dir/bil/entry.cc.s
.PHONY : bil/entry.cc.s

bil/noop_scheduler.o: bil/noop_scheduler.cc.o

.PHONY : bil/noop_scheduler.o

# target to build an object file
bil/noop_scheduler.cc.o:
	$(MAKE) -f CMakeFiles/simplessd-standalone.dir/build.make CMakeFiles/simplessd-standalone.dir/bil/noop_scheduler.cc.o
.PHONY : bil/noop_scheduler.cc.o

bil/noop_scheduler.i: bil/noop_scheduler.cc.i

.PHONY : bil/noop_scheduler.i

# target to preprocess a source file
bil/noop_scheduler.cc.i:
	$(MAKE) -f CMakeFiles/simplessd-standalone.dir/build.make CMakeFiles/simplessd-standalone.dir/bil/noop_scheduler.cc.i
.PHONY : bil/noop_scheduler.cc.i

bil/noop_scheduler.s: bil/noop_scheduler.cc.s

.PHONY : bil/noop_scheduler.s

# target to generate assembly for a file
bil/noop_scheduler.cc.s:
	$(MAKE) -f CMakeFiles/simplessd-standalone.dir/build.make CMakeFiles/simplessd-standalone.dir/bil/noop_scheduler.cc.s
.PHONY : bil/noop_scheduler.cc.s

igl/request/request_config.o: igl/request/request_config.cc.o

.PHONY : igl/request/request_config.o

# target to build an object file
igl/request/request_config.cc.o:
	$(MAKE) -f CMakeFiles/simplessd-standalone.dir/build.make CMakeFiles/simplessd-standalone.dir/igl/request/request_config.cc.o
.PHONY : igl/request/request_config.cc.o

igl/request/request_config.i: igl/request/request_config.cc.i

.PHONY : igl/request/request_config.i

# target to preprocess a source file
igl/request/request_config.cc.i:
	$(MAKE) -f CMakeFiles/simplessd-standalone.dir/build.make CMakeFiles/simplessd-standalone.dir/igl/request/request_config.cc.i
.PHONY : igl/request/request_config.cc.i

igl/request/request_config.s: igl/request/request_config.cc.s

.PHONY : igl/request/request_config.s

# target to generate assembly for a file
igl/request/request_config.cc.s:
	$(MAKE) -f CMakeFiles/simplessd-standalone.dir/build.make CMakeFiles/simplessd-standalone.dir/igl/request/request_config.cc.s
.PHONY : igl/request/request_config.cc.s

igl/request/request_generator.o: igl/request/request_generator.cc.o

.PHONY : igl/request/request_generator.o

# target to build an object file
igl/request/request_generator.cc.o:
	$(MAKE) -f CMakeFiles/simplessd-standalone.dir/build.make CMakeFiles/simplessd-standalone.dir/igl/request/request_generator.cc.o
.PHONY : igl/request/request_generator.cc.o

igl/request/request_generator.i: igl/request/request_generator.cc.i

.PHONY : igl/request/request_generator.i

# target to preprocess a source file
igl/request/request_generator.cc.i:
	$(MAKE) -f CMakeFiles/simplessd-standalone.dir/build.make CMakeFiles/simplessd-standalone.dir/igl/request/request_generator.cc.i
.PHONY : igl/request/request_generator.cc.i

igl/request/request_generator.s: igl/request/request_generator.cc.s

.PHONY : igl/request/request_generator.s

# target to generate assembly for a file
igl/request/request_generator.cc.s:
	$(MAKE) -f CMakeFiles/simplessd-standalone.dir/build.make CMakeFiles/simplessd-standalone.dir/igl/request/request_generator.cc.s
.PHONY : igl/request/request_generator.cc.s

igl/trace/trace_config.o: igl/trace/trace_config.cc.o

.PHONY : igl/trace/trace_config.o

# target to build an object file
igl/trace/trace_config.cc.o:
	$(MAKE) -f CMakeFiles/simplessd-standalone.dir/build.make CMakeFiles/simplessd-standalone.dir/igl/trace/trace_config.cc.o
.PHONY : igl/trace/trace_config.cc.o

igl/trace/trace_config.i: igl/trace/trace_config.cc.i

.PHONY : igl/trace/trace_config.i

# target to preprocess a source file
igl/trace/trace_config.cc.i:
	$(MAKE) -f CMakeFiles/simplessd-standalone.dir/build.make CMakeFiles/simplessd-standalone.dir/igl/trace/trace_config.cc.i
.PHONY : igl/trace/trace_config.cc.i

igl/trace/trace_config.s: igl/trace/trace_config.cc.s

.PHONY : igl/trace/trace_config.s

# target to generate assembly for a file
igl/trace/trace_config.cc.s:
	$(MAKE) -f CMakeFiles/simplessd-standalone.dir/build.make CMakeFiles/simplessd-standalone.dir/igl/trace/trace_config.cc.s
.PHONY : igl/trace/trace_config.cc.s

igl/trace/trace_replayer.o: igl/trace/trace_replayer.cc.o

.PHONY : igl/trace/trace_replayer.o

# target to build an object file
igl/trace/trace_replayer.cc.o:
	$(MAKE) -f CMakeFiles/simplessd-standalone.dir/build.make CMakeFiles/simplessd-standalone.dir/igl/trace/trace_replayer.cc.o
.PHONY : igl/trace/trace_replayer.cc.o

igl/trace/trace_replayer.i: igl/trace/trace_replayer.cc.i

.PHONY : igl/trace/trace_replayer.i

# target to preprocess a source file
igl/trace/trace_replayer.cc.i:
	$(MAKE) -f CMakeFiles/simplessd-standalone.dir/build.make CMakeFiles/simplessd-standalone.dir/igl/trace/trace_replayer.cc.i
.PHONY : igl/trace/trace_replayer.cc.i

igl/trace/trace_replayer.s: igl/trace/trace_replayer.cc.s

.PHONY : igl/trace/trace_replayer.s

# target to generate assembly for a file
igl/trace/trace_replayer.cc.s:
	$(MAKE) -f CMakeFiles/simplessd-standalone.dir/build.make CMakeFiles/simplessd-standalone.dir/igl/trace/trace_replayer.cc.s
.PHONY : igl/trace/trace_replayer.cc.s

lib/drampower/src/CAHelpers.o: lib/drampower/src/CAHelpers.cc.o

.PHONY : lib/drampower/src/CAHelpers.o

# target to build an object file
lib/drampower/src/CAHelpers.cc.o:
	$(MAKE) -f CMakeFiles/simplessd-standalone.dir/build.make CMakeFiles/simplessd-standalone.dir/lib/drampower/src/CAHelpers.cc.o
.PHONY : lib/drampower/src/CAHelpers.cc.o

lib/drampower/src/CAHelpers.i: lib/drampower/src/CAHelpers.cc.i

.PHONY : lib/drampower/src/CAHelpers.i

# target to preprocess a source file
lib/drampower/src/CAHelpers.cc.i:
	$(MAKE) -f CMakeFiles/simplessd-standalone.dir/build.make CMakeFiles/simplessd-standalone.dir/lib/drampower/src/CAHelpers.cc.i
.PHONY : lib/drampower/src/CAHelpers.cc.i

lib/drampower/src/CAHelpers.s: lib/drampower/src/CAHelpers.cc.s

.PHONY : lib/drampower/src/CAHelpers.s

# target to generate assembly for a file
lib/drampower/src/CAHelpers.cc.s:
	$(MAKE) -f CMakeFiles/simplessd-standalone.dir/build.make CMakeFiles/simplessd-standalone.dir/lib/drampower/src/CAHelpers.cc.s
.PHONY : lib/drampower/src/CAHelpers.cc.s

lib/drampower/src/CmdHandlers.o: lib/drampower/src/CmdHandlers.cc.o

.PHONY : lib/drampower/src/CmdHandlers.o

# target to build an object file
lib/drampower/src/CmdHandlers.cc.o:
	$(MAKE) -f CMakeFiles/simplessd-standalone.dir/build.make CMakeFiles/simplessd-standalone.dir/lib/drampower/src/CmdHandlers.cc.o
.PHONY : lib/drampower/src/CmdHandlers.cc.o

lib/drampower/src/CmdHandlers.i: lib/drampower/src/CmdHandlers.cc.i

.PHONY : lib/drampower/src/CmdHandlers.i

# target to preprocess a source file
lib/drampower/src/CmdHandlers.cc.i:
	$(MAKE) -f CMakeFiles/simplessd-standalone.dir/build.make CMakeFiles/simplessd-standalone.dir/lib/drampower/src/CmdHandlers.cc.i
.PHONY : lib/drampower/src/CmdHandlers.cc.i

lib/drampower/src/CmdHandlers.s: lib/drampower/src/CmdHandlers.cc.s

.PHONY : lib/drampower/src/CmdHandlers.s

# target to generate assembly for a file
lib/drampower/src/CmdHandlers.cc.s:
	$(MAKE) -f CMakeFiles/simplessd-standalone.dir/build.make CMakeFiles/simplessd-standalone.dir/lib/drampower/src/CmdHandlers.cc.s
.PHONY : lib/drampower/src/CmdHandlers.cc.s

lib/drampower/src/CmdScheduler.o: lib/drampower/src/CmdScheduler.cc.o

.PHONY : lib/drampower/src/CmdScheduler.o

# target to build an object file
lib/drampower/src/CmdScheduler.cc.o:
	$(MAKE) -f CMakeFiles/simplessd-standalone.dir/build.make CMakeFiles/simplessd-standalone.dir/lib/drampower/src/CmdScheduler.cc.o
.PHONY : lib/drampower/src/CmdScheduler.cc.o

lib/drampower/src/CmdScheduler.i: lib/drampower/src/CmdScheduler.cc.i

.PHONY : lib/drampower/src/CmdScheduler.i

# target to preprocess a source file
lib/drampower/src/CmdScheduler.cc.i:
	$(MAKE) -f CMakeFiles/simplessd-standalone.dir/build.make CMakeFiles/simplessd-standalone.dir/lib/drampower/src/CmdScheduler.cc.i
.PHONY : lib/drampower/src/CmdScheduler.cc.i

lib/drampower/src/CmdScheduler.s: lib/drampower/src/CmdScheduler.cc.s

.PHONY : lib/drampower/src/CmdScheduler.s

# target to generate assembly for a file
lib/drampower/src/CmdScheduler.cc.s:
	$(MAKE) -f CMakeFiles/simplessd-standalone.dir/build.make CMakeFiles/simplessd-standalone.dir/lib/drampower/src/CmdScheduler.cc.s
.PHONY : lib/drampower/src/CmdScheduler.cc.s

lib/drampower/src/CommandAnalysis.o: lib/drampower/src/CommandAnalysis.cc.o

.PHONY : lib/drampower/src/CommandAnalysis.o

# target to build an object file
lib/drampower/src/CommandAnalysis.cc.o:
	$(MAKE) -f CMakeFiles/simplessd-standalone.dir/build.make CMakeFiles/simplessd-standalone.dir/lib/drampower/src/CommandAnalysis.cc.o
.PHONY : lib/drampower/src/CommandAnalysis.cc.o

lib/drampower/src/CommandAnalysis.i: lib/drampower/src/CommandAnalysis.cc.i

.PHONY : lib/drampower/src/CommandAnalysis.i

# target to preprocess a source file
lib/drampower/src/CommandAnalysis.cc.i:
	$(MAKE) -f CMakeFiles/simplessd-standalone.dir/build.make CMakeFiles/simplessd-standalone.dir/lib/drampower/src/CommandAnalysis.cc.i
.PHONY : lib/drampower/src/CommandAnalysis.cc.i

lib/drampower/src/CommandAnalysis.s: lib/drampower/src/CommandAnalysis.cc.s

.PHONY : lib/drampower/src/CommandAnalysis.s

# target to generate assembly for a file
lib/drampower/src/CommandAnalysis.cc.s:
	$(MAKE) -f CMakeFiles/simplessd-standalone.dir/build.make CMakeFiles/simplessd-standalone.dir/lib/drampower/src/CommandAnalysis.cc.s
.PHONY : lib/drampower/src/CommandAnalysis.cc.s

lib/drampower/src/MemArchitectureSpec.o: lib/drampower/src/MemArchitectureSpec.cc.o

.PHONY : lib/drampower/src/MemArchitectureSpec.o

# target to build an object file
lib/drampower/src/MemArchitectureSpec.cc.o:
	$(MAKE) -f CMakeFiles/simplessd-standalone.dir/build.make CMakeFiles/simplessd-standalone.dir/lib/drampower/src/MemArchitectureSpec.cc.o
.PHONY : lib/drampower/src/MemArchitectureSpec.cc.o

lib/drampower/src/MemArchitectureSpec.i: lib/drampower/src/MemArchitectureSpec.cc.i

.PHONY : lib/drampower/src/MemArchitectureSpec.i

# target to preprocess a source file
lib/drampower/src/MemArchitectureSpec.cc.i:
	$(MAKE) -f CMakeFiles/simplessd-standalone.dir/build.make CMakeFiles/simplessd-standalone.dir/lib/drampower/src/MemArchitectureSpec.cc.i
.PHONY : lib/drampower/src/MemArchitectureSpec.cc.i

lib/drampower/src/MemArchitectureSpec.s: lib/drampower/src/MemArchitectureSpec.cc.s

.PHONY : lib/drampower/src/MemArchitectureSpec.s

# target to generate assembly for a file
lib/drampower/src/MemArchitectureSpec.cc.s:
	$(MAKE) -f CMakeFiles/simplessd-standalone.dir/build.make CMakeFiles/simplessd-standalone.dir/lib/drampower/src/MemArchitectureSpec.cc.s
.PHONY : lib/drampower/src/MemArchitectureSpec.cc.s

lib/drampower/src/MemBankWiseParams.o: lib/drampower/src/MemBankWiseParams.cc.o

.PHONY : lib/drampower/src/MemBankWiseParams.o

# target to build an object file
lib/drampower/src/MemBankWiseParams.cc.o:
	$(MAKE) -f CMakeFiles/simplessd-standalone.dir/build.make CMakeFiles/simplessd-standalone.dir/lib/drampower/src/MemBankWiseParams.cc.o
.PHONY : lib/drampower/src/MemBankWiseParams.cc.o

lib/drampower/src/MemBankWiseParams.i: lib/drampower/src/MemBankWiseParams.cc.i

.PHONY : lib/drampower/src/MemBankWiseParams.i

# target to preprocess a source file
lib/drampower/src/MemBankWiseParams.cc.i:
	$(MAKE) -f CMakeFiles/simplessd-standalone.dir/build.make CMakeFiles/simplessd-standalone.dir/lib/drampower/src/MemBankWiseParams.cc.i
.PHONY : lib/drampower/src/MemBankWiseParams.cc.i

lib/drampower/src/MemBankWiseParams.s: lib/drampower/src/MemBankWiseParams.cc.s

.PHONY : lib/drampower/src/MemBankWiseParams.s

# target to generate assembly for a file
lib/drampower/src/MemBankWiseParams.cc.s:
	$(MAKE) -f CMakeFiles/simplessd-standalone.dir/build.make CMakeFiles/simplessd-standalone.dir/lib/drampower/src/MemBankWiseParams.cc.s
.PHONY : lib/drampower/src/MemBankWiseParams.cc.s

lib/drampower/src/MemCommand.o: lib/drampower/src/MemCommand.cc.o

.PHONY : lib/drampower/src/MemCommand.o

# target to build an object file
lib/drampower/src/MemCommand.cc.o:
	$(MAKE) -f CMakeFiles/simplessd-standalone.dir/build.make CMakeFiles/simplessd-standalone.dir/lib/drampower/src/MemCommand.cc.o
.PHONY : lib/drampower/src/MemCommand.cc.o

lib/drampower/src/MemCommand.i: lib/drampower/src/MemCommand.cc.i

.PHONY : lib/drampower/src/MemCommand.i

# target to preprocess a source file
lib/drampower/src/MemCommand.cc.i:
	$(MAKE) -f CMakeFiles/simplessd-standalone.dir/build.make CMakeFiles/simplessd-standalone.dir/lib/drampower/src/MemCommand.cc.i
.PHONY : lib/drampower/src/MemCommand.cc.i

lib/drampower/src/MemCommand.s: lib/drampower/src/MemCommand.cc.s

.PHONY : lib/drampower/src/MemCommand.s

# target to generate assembly for a file
lib/drampower/src/MemCommand.cc.s:
	$(MAKE) -f CMakeFiles/simplessd-standalone.dir/build.make CMakeFiles/simplessd-standalone.dir/lib/drampower/src/MemCommand.cc.s
.PHONY : lib/drampower/src/MemCommand.cc.s

lib/drampower/src/MemPowerSpec.o: lib/drampower/src/MemPowerSpec.cc.o

.PHONY : lib/drampower/src/MemPowerSpec.o

# target to build an object file
lib/drampower/src/MemPowerSpec.cc.o:
	$(MAKE) -f CMakeFiles/simplessd-standalone.dir/build.make CMakeFiles/simplessd-standalone.dir/lib/drampower/src/MemPowerSpec.cc.o
.PHONY : lib/drampower/src/MemPowerSpec.cc.o

lib/drampower/src/MemPowerSpec.i: lib/drampower/src/MemPowerSpec.cc.i

.PHONY : lib/drampower/src/MemPowerSpec.i

# target to preprocess a source file
lib/drampower/src/MemPowerSpec.cc.i:
	$(MAKE) -f CMakeFiles/simplessd-standalone.dir/build.make CMakeFiles/simplessd-standalone.dir/lib/drampower/src/MemPowerSpec.cc.i
.PHONY : lib/drampower/src/MemPowerSpec.cc.i

lib/drampower/src/MemPowerSpec.s: lib/drampower/src/MemPowerSpec.cc.s

.PHONY : lib/drampower/src/MemPowerSpec.s

# target to generate assembly for a file
lib/drampower/src/MemPowerSpec.cc.s:
	$(MAKE) -f CMakeFiles/simplessd-standalone.dir/build.make CMakeFiles/simplessd-standalone.dir/lib/drampower/src/MemPowerSpec.cc.s
.PHONY : lib/drampower/src/MemPowerSpec.cc.s

lib/drampower/src/MemTimingSpec.o: lib/drampower/src/MemTimingSpec.cc.o

.PHONY : lib/drampower/src/MemTimingSpec.o

# target to build an object file
lib/drampower/src/MemTimingSpec.cc.o:
	$(MAKE) -f CMakeFiles/simplessd-standalone.dir/build.make CMakeFiles/simplessd-standalone.dir/lib/drampower/src/MemTimingSpec.cc.o
.PHONY : lib/drampower/src/MemTimingSpec.cc.o

lib/drampower/src/MemTimingSpec.i: lib/drampower/src/MemTimingSpec.cc.i

.PHONY : lib/drampower/src/MemTimingSpec.i

# target to preprocess a source file
lib/drampower/src/MemTimingSpec.cc.i:
	$(MAKE) -f CMakeFiles/simplessd-standalone.dir/build.make CMakeFiles/simplessd-standalone.dir/lib/drampower/src/MemTimingSpec.cc.i
.PHONY : lib/drampower/src/MemTimingSpec.cc.i

lib/drampower/src/MemTimingSpec.s: lib/drampower/src/MemTimingSpec.cc.s

.PHONY : lib/drampower/src/MemTimingSpec.s

# target to generate assembly for a file
lib/drampower/src/MemTimingSpec.cc.s:
	$(MAKE) -f CMakeFiles/simplessd-standalone.dir/build.make CMakeFiles/simplessd-standalone.dir/lib/drampower/src/MemTimingSpec.cc.s
.PHONY : lib/drampower/src/MemTimingSpec.cc.s

lib/drampower/src/MemoryPowerModel.o: lib/drampower/src/MemoryPowerModel.cc.o

.PHONY : lib/drampower/src/MemoryPowerModel.o

# target to build an object file
lib/drampower/src/MemoryPowerModel.cc.o:
	$(MAKE) -f CMakeFiles/simplessd-standalone.dir/build.make CMakeFiles/simplessd-standalone.dir/lib/drampower/src/MemoryPowerModel.cc.o
.PHONY : lib/drampower/src/MemoryPowerModel.cc.o

lib/drampower/src/MemoryPowerModel.i: lib/drampower/src/MemoryPowerModel.cc.i

.PHONY : lib/drampower/src/MemoryPowerModel.i

# target to preprocess a source file
lib/drampower/src/MemoryPowerModel.cc.i:
	$(MAKE) -f CMakeFiles/simplessd-standalone.dir/build.make CMakeFiles/simplessd-standalone.dir/lib/drampower/src/MemoryPowerModel.cc.i
.PHONY : lib/drampower/src/MemoryPowerModel.cc.i

lib/drampower/src/MemoryPowerModel.s: lib/drampower/src/MemoryPowerModel.cc.s

.PHONY : lib/drampower/src/MemoryPowerModel.s

# target to generate assembly for a file
lib/drampower/src/MemoryPowerModel.cc.s:
	$(MAKE) -f CMakeFiles/simplessd-standalone.dir/build.make CMakeFiles/simplessd-standalone.dir/lib/drampower/src/MemoryPowerModel.cc.s
.PHONY : lib/drampower/src/MemoryPowerModel.cc.s

lib/drampower/src/MemorySpecification.o: lib/drampower/src/MemorySpecification.cc.o

.PHONY : lib/drampower/src/MemorySpecification.o

# target to build an object file
lib/drampower/src/MemorySpecification.cc.o:
	$(MAKE) -f CMakeFiles/simplessd-standalone.dir/build.make CMakeFiles/simplessd-standalone.dir/lib/drampower/src/MemorySpecification.cc.o
.PHONY : lib/drampower/src/MemorySpecification.cc.o

lib/drampower/src/MemorySpecification.i: lib/drampower/src/MemorySpecification.cc.i

.PHONY : lib/drampower/src/MemorySpecification.i

# target to preprocess a source file
lib/drampower/src/MemorySpecification.cc.i:
	$(MAKE) -f CMakeFiles/simplessd-standalone.dir/build.make CMakeFiles/simplessd-standalone.dir/lib/drampower/src/MemorySpecification.cc.i
.PHONY : lib/drampower/src/MemorySpecification.cc.i

lib/drampower/src/MemorySpecification.s: lib/drampower/src/MemorySpecification.cc.s

.PHONY : lib/drampower/src/MemorySpecification.s

# target to generate assembly for a file
lib/drampower/src/MemorySpecification.cc.s:
	$(MAKE) -f CMakeFiles/simplessd-standalone.dir/build.make CMakeFiles/simplessd-standalone.dir/lib/drampower/src/MemorySpecification.cc.s
.PHONY : lib/drampower/src/MemorySpecification.cc.s

lib/drampower/src/Parameter.o: lib/drampower/src/Parameter.cc.o

.PHONY : lib/drampower/src/Parameter.o

# target to build an object file
lib/drampower/src/Parameter.cc.o:
	$(MAKE) -f CMakeFiles/simplessd-standalone.dir/build.make CMakeFiles/simplessd-standalone.dir/lib/drampower/src/Parameter.cc.o
.PHONY : lib/drampower/src/Parameter.cc.o

lib/drampower/src/Parameter.i: lib/drampower/src/Parameter.cc.i

.PHONY : lib/drampower/src/Parameter.i

# target to preprocess a source file
lib/drampower/src/Parameter.cc.i:
	$(MAKE) -f CMakeFiles/simplessd-standalone.dir/build.make CMakeFiles/simplessd-standalone.dir/lib/drampower/src/Parameter.cc.i
.PHONY : lib/drampower/src/Parameter.cc.i

lib/drampower/src/Parameter.s: lib/drampower/src/Parameter.cc.s

.PHONY : lib/drampower/src/Parameter.s

# target to generate assembly for a file
lib/drampower/src/Parameter.cc.s:
	$(MAKE) -f CMakeFiles/simplessd-standalone.dir/build.make CMakeFiles/simplessd-standalone.dir/lib/drampower/src/Parameter.cc.s
.PHONY : lib/drampower/src/Parameter.cc.s

lib/drampower/src/Parametrisable.o: lib/drampower/src/Parametrisable.cc.o

.PHONY : lib/drampower/src/Parametrisable.o

# target to build an object file
lib/drampower/src/Parametrisable.cc.o:
	$(MAKE) -f CMakeFiles/simplessd-standalone.dir/build.make CMakeFiles/simplessd-standalone.dir/lib/drampower/src/Parametrisable.cc.o
.PHONY : lib/drampower/src/Parametrisable.cc.o

lib/drampower/src/Parametrisable.i: lib/drampower/src/Parametrisable.cc.i

.PHONY : lib/drampower/src/Parametrisable.i

# target to preprocess a source file
lib/drampower/src/Parametrisable.cc.i:
	$(MAKE) -f CMakeFiles/simplessd-standalone.dir/build.make CMakeFiles/simplessd-standalone.dir/lib/drampower/src/Parametrisable.cc.i
.PHONY : lib/drampower/src/Parametrisable.cc.i

lib/drampower/src/Parametrisable.s: lib/drampower/src/Parametrisable.cc.s

.PHONY : lib/drampower/src/Parametrisable.s

# target to generate assembly for a file
lib/drampower/src/Parametrisable.cc.s:
	$(MAKE) -f CMakeFiles/simplessd-standalone.dir/build.make CMakeFiles/simplessd-standalone.dir/lib/drampower/src/Parametrisable.cc.s
.PHONY : lib/drampower/src/Parametrisable.cc.s

lib/drampower/src/TraceParser.o: lib/drampower/src/TraceParser.cc.o

.PHONY : lib/drampower/src/TraceParser.o

# target to build an object file
lib/drampower/src/TraceParser.cc.o:
	$(MAKE) -f CMakeFiles/simplessd-standalone.dir/build.make CMakeFiles/simplessd-standalone.dir/lib/drampower/src/TraceParser.cc.o
.PHONY : lib/drampower/src/TraceParser.cc.o

lib/drampower/src/TraceParser.i: lib/drampower/src/TraceParser.cc.i

.PHONY : lib/drampower/src/TraceParser.i

# target to preprocess a source file
lib/drampower/src/TraceParser.cc.i:
	$(MAKE) -f CMakeFiles/simplessd-standalone.dir/build.make CMakeFiles/simplessd-standalone.dir/lib/drampower/src/TraceParser.cc.i
.PHONY : lib/drampower/src/TraceParser.cc.i

lib/drampower/src/TraceParser.s: lib/drampower/src/TraceParser.cc.s

.PHONY : lib/drampower/src/TraceParser.s

# target to generate assembly for a file
lib/drampower/src/TraceParser.cc.s:
	$(MAKE) -f CMakeFiles/simplessd-standalone.dir/build.make CMakeFiles/simplessd-standalone.dir/lib/drampower/src/TraceParser.cc.s
.PHONY : lib/drampower/src/TraceParser.cc.s

lib/drampower/src/libdrampower/LibDRAMPower.o: lib/drampower/src/libdrampower/LibDRAMPower.cc.o

.PHONY : lib/drampower/src/libdrampower/LibDRAMPower.o

# target to build an object file
lib/drampower/src/libdrampower/LibDRAMPower.cc.o:
	$(MAKE) -f CMakeFiles/simplessd-standalone.dir/build.make CMakeFiles/simplessd-standalone.dir/lib/drampower/src/libdrampower/LibDRAMPower.cc.o
.PHONY : lib/drampower/src/libdrampower/LibDRAMPower.cc.o

lib/drampower/src/libdrampower/LibDRAMPower.i: lib/drampower/src/libdrampower/LibDRAMPower.cc.i

.PHONY : lib/drampower/src/libdrampower/LibDRAMPower.i

# target to preprocess a source file
lib/drampower/src/libdrampower/LibDRAMPower.cc.i:
	$(MAKE) -f CMakeFiles/simplessd-standalone.dir/build.make CMakeFiles/simplessd-standalone.dir/lib/drampower/src/libdrampower/LibDRAMPower.cc.i
.PHONY : lib/drampower/src/libdrampower/LibDRAMPower.cc.i

lib/drampower/src/libdrampower/LibDRAMPower.s: lib/drampower/src/libdrampower/LibDRAMPower.cc.s

.PHONY : lib/drampower/src/libdrampower/LibDRAMPower.s

# target to generate assembly for a file
lib/drampower/src/libdrampower/LibDRAMPower.cc.s:
	$(MAKE) -f CMakeFiles/simplessd-standalone.dir/build.make CMakeFiles/simplessd-standalone.dir/lib/drampower/src/libdrampower/LibDRAMPower.cc.s
.PHONY : lib/drampower/src/libdrampower/LibDRAMPower.cc.s

sil/none/none.o: sil/none/none.cc.o

.PHONY : sil/none/none.o

# target to build an object file
sil/none/none.cc.o:
	$(MAKE) -f CMakeFiles/simplessd-standalone.dir/build.make CMakeFiles/simplessd-standalone.dir/sil/none/none.cc.o
.PHONY : sil/none/none.cc.o

sil/none/none.i: sil/none/none.cc.i

.PHONY : sil/none/none.i

# target to preprocess a source file
sil/none/none.cc.i:
	$(MAKE) -f CMakeFiles/simplessd-standalone.dir/build.make CMakeFiles/simplessd-standalone.dir/sil/none/none.cc.i
.PHONY : sil/none/none.cc.i

sil/none/none.s: sil/none/none.cc.s

.PHONY : sil/none/none.s

# target to generate assembly for a file
sil/none/none.cc.s:
	$(MAKE) -f CMakeFiles/simplessd-standalone.dir/build.make CMakeFiles/simplessd-standalone.dir/sil/none/none.cc.s
.PHONY : sil/none/none.cc.s

sil/nvme/nvme.o: sil/nvme/nvme.cc.o

.PHONY : sil/nvme/nvme.o

# target to build an object file
sil/nvme/nvme.cc.o:
	$(MAKE) -f CMakeFiles/simplessd-standalone.dir/build.make CMakeFiles/simplessd-standalone.dir/sil/nvme/nvme.cc.o
.PHONY : sil/nvme/nvme.cc.o

sil/nvme/nvme.i: sil/nvme/nvme.cc.i

.PHONY : sil/nvme/nvme.i

# target to preprocess a source file
sil/nvme/nvme.cc.i:
	$(MAKE) -f CMakeFiles/simplessd-standalone.dir/build.make CMakeFiles/simplessd-standalone.dir/sil/nvme/nvme.cc.i
.PHONY : sil/nvme/nvme.cc.i

sil/nvme/nvme.s: sil/nvme/nvme.cc.s

.PHONY : sil/nvme/nvme.s

# target to generate assembly for a file
sil/nvme/nvme.cc.s:
	$(MAKE) -f CMakeFiles/simplessd-standalone.dir/build.make CMakeFiles/simplessd-standalone.dir/sil/nvme/nvme.cc.s
.PHONY : sil/nvme/nvme.cc.s

sil/nvme/prp.o: sil/nvme/prp.cc.o

.PHONY : sil/nvme/prp.o

# target to build an object file
sil/nvme/prp.cc.o:
	$(MAKE) -f CMakeFiles/simplessd-standalone.dir/build.make CMakeFiles/simplessd-standalone.dir/sil/nvme/prp.cc.o
.PHONY : sil/nvme/prp.cc.o

sil/nvme/prp.i: sil/nvme/prp.cc.i

.PHONY : sil/nvme/prp.i

# target to preprocess a source file
sil/nvme/prp.cc.i:
	$(MAKE) -f CMakeFiles/simplessd-standalone.dir/build.make CMakeFiles/simplessd-standalone.dir/sil/nvme/prp.cc.i
.PHONY : sil/nvme/prp.cc.i

sil/nvme/prp.s: sil/nvme/prp.cc.s

.PHONY : sil/nvme/prp.s

# target to generate assembly for a file
sil/nvme/prp.cc.s:
	$(MAKE) -f CMakeFiles/simplessd-standalone.dir/build.make CMakeFiles/simplessd-standalone.dir/sil/nvme/prp.cc.s
.PHONY : sil/nvme/prp.cc.s

sil/nvme/queue.o: sil/nvme/queue.cc.o

.PHONY : sil/nvme/queue.o

# target to build an object file
sil/nvme/queue.cc.o:
	$(MAKE) -f CMakeFiles/simplessd-standalone.dir/build.make CMakeFiles/simplessd-standalone.dir/sil/nvme/queue.cc.o
.PHONY : sil/nvme/queue.cc.o

sil/nvme/queue.i: sil/nvme/queue.cc.i

.PHONY : sil/nvme/queue.i

# target to preprocess a source file
sil/nvme/queue.cc.i:
	$(MAKE) -f CMakeFiles/simplessd-standalone.dir/build.make CMakeFiles/simplessd-standalone.dir/sil/nvme/queue.cc.i
.PHONY : sil/nvme/queue.cc.i

sil/nvme/queue.s: sil/nvme/queue.cc.s

.PHONY : sil/nvme/queue.s

# target to generate assembly for a file
sil/nvme/queue.cc.s:
	$(MAKE) -f CMakeFiles/simplessd-standalone.dir/build.make CMakeFiles/simplessd-standalone.dir/sil/nvme/queue.cc.s
.PHONY : sil/nvme/queue.cc.s

sim/cfg_reader.o: sim/cfg_reader.cc.o

.PHONY : sim/cfg_reader.o

# target to build an object file
sim/cfg_reader.cc.o:
	$(MAKE) -f CMakeFiles/simplessd-standalone.dir/build.make CMakeFiles/simplessd-standalone.dir/sim/cfg_reader.cc.o
.PHONY : sim/cfg_reader.cc.o

sim/cfg_reader.i: sim/cfg_reader.cc.i

.PHONY : sim/cfg_reader.i

# target to preprocess a source file
sim/cfg_reader.cc.i:
	$(MAKE) -f CMakeFiles/simplessd-standalone.dir/build.make CMakeFiles/simplessd-standalone.dir/sim/cfg_reader.cc.i
.PHONY : sim/cfg_reader.cc.i

sim/cfg_reader.s: sim/cfg_reader.cc.s

.PHONY : sim/cfg_reader.s

# target to generate assembly for a file
sim/cfg_reader.cc.s:
	$(MAKE) -f CMakeFiles/simplessd-standalone.dir/build.make CMakeFiles/simplessd-standalone.dir/sim/cfg_reader.cc.s
.PHONY : sim/cfg_reader.cc.s

sim/engine.o: sim/engine.cc.o

.PHONY : sim/engine.o

# target to build an object file
sim/engine.cc.o:
	$(MAKE) -f CMakeFiles/simplessd-standalone.dir/build.make CMakeFiles/simplessd-standalone.dir/sim/engine.cc.o
.PHONY : sim/engine.cc.o

sim/engine.i: sim/engine.cc.i

.PHONY : sim/engine.i

# target to preprocess a source file
sim/engine.cc.i:
	$(MAKE) -f CMakeFiles/simplessd-standalone.dir/build.make CMakeFiles/simplessd-standalone.dir/sim/engine.cc.i
.PHONY : sim/engine.cc.i

sim/engine.s: sim/engine.cc.s

.PHONY : sim/engine.s

# target to generate assembly for a file
sim/engine.cc.s:
	$(MAKE) -f CMakeFiles/simplessd-standalone.dir/build.make CMakeFiles/simplessd-standalone.dir/sim/engine.cc.s
.PHONY : sim/engine.cc.s

sim/global_config.o: sim/global_config.cc.o

.PHONY : sim/global_config.o

# target to build an object file
sim/global_config.cc.o:
	$(MAKE) -f CMakeFiles/simplessd-standalone.dir/build.make CMakeFiles/simplessd-standalone.dir/sim/global_config.cc.o
.PHONY : sim/global_config.cc.o

sim/global_config.i: sim/global_config.cc.i

.PHONY : sim/global_config.i

# target to preprocess a source file
sim/global_config.cc.i:
	$(MAKE) -f CMakeFiles/simplessd-standalone.dir/build.make CMakeFiles/simplessd-standalone.dir/sim/global_config.cc.i
.PHONY : sim/global_config.cc.i

sim/global_config.s: sim/global_config.cc.s

.PHONY : sim/global_config.s

# target to generate assembly for a file
sim/global_config.cc.s:
	$(MAKE) -f CMakeFiles/simplessd-standalone.dir/build.make CMakeFiles/simplessd-standalone.dir/sim/global_config.cc.s
.PHONY : sim/global_config.cc.s

sim/main.o: sim/main.cc.o

.PHONY : sim/main.o

# target to build an object file
sim/main.cc.o:
	$(MAKE) -f CMakeFiles/simplessd-standalone.dir/build.make CMakeFiles/simplessd-standalone.dir/sim/main.cc.o
.PHONY : sim/main.cc.o

sim/main.i: sim/main.cc.i

.PHONY : sim/main.i

# target to preprocess a source file
sim/main.cc.i:
	$(MAKE) -f CMakeFiles/simplessd-standalone.dir/build.make CMakeFiles/simplessd-standalone.dir/sim/main.cc.i
.PHONY : sim/main.cc.i

sim/main.s: sim/main.cc.s

.PHONY : sim/main.s

# target to generate assembly for a file
sim/main.cc.s:
	$(MAKE) -f CMakeFiles/simplessd-standalone.dir/build.make CMakeFiles/simplessd-standalone.dir/sim/main.cc.s
.PHONY : sim/main.cc.s

sim/signal.o: sim/signal.cc.o

.PHONY : sim/signal.o

# target to build an object file
sim/signal.cc.o:
	$(MAKE) -f CMakeFiles/simplessd-standalone.dir/build.make CMakeFiles/simplessd-standalone.dir/sim/signal.cc.o
.PHONY : sim/signal.cc.o

sim/signal.i: sim/signal.cc.i

.PHONY : sim/signal.i

# target to preprocess a source file
sim/signal.cc.i:
	$(MAKE) -f CMakeFiles/simplessd-standalone.dir/build.make CMakeFiles/simplessd-standalone.dir/sim/signal.cc.i
.PHONY : sim/signal.cc.i

sim/signal.s: sim/signal.cc.s

.PHONY : sim/signal.s

# target to generate assembly for a file
sim/signal.cc.s:
	$(MAKE) -f CMakeFiles/simplessd-standalone.dir/build.make CMakeFiles/simplessd-standalone.dir/sim/signal.cc.s
.PHONY : sim/signal.cc.s

util/convert.o: util/convert.cc.o

.PHONY : util/convert.o

# target to build an object file
util/convert.cc.o:
	$(MAKE) -f CMakeFiles/simplessd-standalone.dir/build.make CMakeFiles/simplessd-standalone.dir/util/convert.cc.o
.PHONY : util/convert.cc.o

util/convert.i: util/convert.cc.i

.PHONY : util/convert.i

# target to preprocess a source file
util/convert.cc.i:
	$(MAKE) -f CMakeFiles/simplessd-standalone.dir/build.make CMakeFiles/simplessd-standalone.dir/util/convert.cc.i
.PHONY : util/convert.cc.i

util/convert.s: util/convert.cc.s

.PHONY : util/convert.s

# target to generate assembly for a file
util/convert.cc.s:
	$(MAKE) -f CMakeFiles/simplessd-standalone.dir/build.make CMakeFiles/simplessd-standalone.dir/util/convert.cc.s
.PHONY : util/convert.cc.s

util/print.o: util/print.cc.o

.PHONY : util/print.o

# target to build an object file
util/print.cc.o:
	$(MAKE) -f CMakeFiles/simplessd-standalone.dir/build.make CMakeFiles/simplessd-standalone.dir/util/print.cc.o
.PHONY : util/print.cc.o

util/print.i: util/print.cc.i

.PHONY : util/print.i

# target to preprocess a source file
util/print.cc.i:
	$(MAKE) -f CMakeFiles/simplessd-standalone.dir/build.make CMakeFiles/simplessd-standalone.dir/util/print.cc.i
.PHONY : util/print.cc.i

util/print.s: util/print.cc.s

.PHONY : util/print.s

# target to generate assembly for a file
util/print.cc.s:
	$(MAKE) -f CMakeFiles/simplessd-standalone.dir/build.make CMakeFiles/simplessd-standalone.dir/util/print.cc.s
.PHONY : util/print.cc.s

util/stopwatch.o: util/stopwatch.cc.o

.PHONY : util/stopwatch.o

# target to build an object file
util/stopwatch.cc.o:
	$(MAKE) -f CMakeFiles/simplessd-standalone.dir/build.make CMakeFiles/simplessd-standalone.dir/util/stopwatch.cc.o
.PHONY : util/stopwatch.cc.o

util/stopwatch.i: util/stopwatch.cc.i

.PHONY : util/stopwatch.i

# target to preprocess a source file
util/stopwatch.cc.i:
	$(MAKE) -f CMakeFiles/simplessd-standalone.dir/build.make CMakeFiles/simplessd-standalone.dir/util/stopwatch.cc.i
.PHONY : util/stopwatch.cc.i

util/stopwatch.s: util/stopwatch.cc.s

.PHONY : util/stopwatch.s

# target to generate assembly for a file
util/stopwatch.cc.s:
	$(MAKE) -f CMakeFiles/simplessd-standalone.dir/build.make CMakeFiles/simplessd-standalone.dir/util/stopwatch.cc.s
.PHONY : util/stopwatch.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... simplessd-standalone"
	@echo "... simplessd"
	@echo "... mcpat"
	@echo "... bil/entry.o"
	@echo "... bil/entry.i"
	@echo "... bil/entry.s"
	@echo "... bil/noop_scheduler.o"
	@echo "... bil/noop_scheduler.i"
	@echo "... bil/noop_scheduler.s"
	@echo "... igl/request/request_config.o"
	@echo "... igl/request/request_config.i"
	@echo "... igl/request/request_config.s"
	@echo "... igl/request/request_generator.o"
	@echo "... igl/request/request_generator.i"
	@echo "... igl/request/request_generator.s"
	@echo "... igl/trace/trace_config.o"
	@echo "... igl/trace/trace_config.i"
	@echo "... igl/trace/trace_config.s"
	@echo "... igl/trace/trace_replayer.o"
	@echo "... igl/trace/trace_replayer.i"
	@echo "... igl/trace/trace_replayer.s"
	@echo "... lib/drampower/src/CAHelpers.o"
	@echo "... lib/drampower/src/CAHelpers.i"
	@echo "... lib/drampower/src/CAHelpers.s"
	@echo "... lib/drampower/src/CmdHandlers.o"
	@echo "... lib/drampower/src/CmdHandlers.i"
	@echo "... lib/drampower/src/CmdHandlers.s"
	@echo "... lib/drampower/src/CmdScheduler.o"
	@echo "... lib/drampower/src/CmdScheduler.i"
	@echo "... lib/drampower/src/CmdScheduler.s"
	@echo "... lib/drampower/src/CommandAnalysis.o"
	@echo "... lib/drampower/src/CommandAnalysis.i"
	@echo "... lib/drampower/src/CommandAnalysis.s"
	@echo "... lib/drampower/src/MemArchitectureSpec.o"
	@echo "... lib/drampower/src/MemArchitectureSpec.i"
	@echo "... lib/drampower/src/MemArchitectureSpec.s"
	@echo "... lib/drampower/src/MemBankWiseParams.o"
	@echo "... lib/drampower/src/MemBankWiseParams.i"
	@echo "... lib/drampower/src/MemBankWiseParams.s"
	@echo "... lib/drampower/src/MemCommand.o"
	@echo "... lib/drampower/src/MemCommand.i"
	@echo "... lib/drampower/src/MemCommand.s"
	@echo "... lib/drampower/src/MemPowerSpec.o"
	@echo "... lib/drampower/src/MemPowerSpec.i"
	@echo "... lib/drampower/src/MemPowerSpec.s"
	@echo "... lib/drampower/src/MemTimingSpec.o"
	@echo "... lib/drampower/src/MemTimingSpec.i"
	@echo "... lib/drampower/src/MemTimingSpec.s"
	@echo "... lib/drampower/src/MemoryPowerModel.o"
	@echo "... lib/drampower/src/MemoryPowerModel.i"
	@echo "... lib/drampower/src/MemoryPowerModel.s"
	@echo "... lib/drampower/src/MemorySpecification.o"
	@echo "... lib/drampower/src/MemorySpecification.i"
	@echo "... lib/drampower/src/MemorySpecification.s"
	@echo "... lib/drampower/src/Parameter.o"
	@echo "... lib/drampower/src/Parameter.i"
	@echo "... lib/drampower/src/Parameter.s"
	@echo "... lib/drampower/src/Parametrisable.o"
	@echo "... lib/drampower/src/Parametrisable.i"
	@echo "... lib/drampower/src/Parametrisable.s"
	@echo "... lib/drampower/src/TraceParser.o"
	@echo "... lib/drampower/src/TraceParser.i"
	@echo "... lib/drampower/src/TraceParser.s"
	@echo "... lib/drampower/src/libdrampower/LibDRAMPower.o"
	@echo "... lib/drampower/src/libdrampower/LibDRAMPower.i"
	@echo "... lib/drampower/src/libdrampower/LibDRAMPower.s"
	@echo "... sil/none/none.o"
	@echo "... sil/none/none.i"
	@echo "... sil/none/none.s"
	@echo "... sil/nvme/nvme.o"
	@echo "... sil/nvme/nvme.i"
	@echo "... sil/nvme/nvme.s"
	@echo "... sil/nvme/prp.o"
	@echo "... sil/nvme/prp.i"
	@echo "... sil/nvme/prp.s"
	@echo "... sil/nvme/queue.o"
	@echo "... sil/nvme/queue.i"
	@echo "... sil/nvme/queue.s"
	@echo "... sim/cfg_reader.o"
	@echo "... sim/cfg_reader.i"
	@echo "... sim/cfg_reader.s"
	@echo "... sim/engine.o"
	@echo "... sim/engine.i"
	@echo "... sim/engine.s"
	@echo "... sim/global_config.o"
	@echo "... sim/global_config.i"
	@echo "... sim/global_config.s"
	@echo "... sim/main.o"
	@echo "... sim/main.i"
	@echo "... sim/main.s"
	@echo "... sim/signal.o"
	@echo "... sim/signal.i"
	@echo "... sim/signal.s"
	@echo "... util/convert.o"
	@echo "... util/convert.i"
	@echo "... util/convert.s"
	@echo "... util/print.o"
	@echo "... util/print.i"
	@echo "... util/print.s"
	@echo "... util/stopwatch.o"
	@echo "... util/stopwatch.i"
	@echo "... util/stopwatch.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

